### ISSUE TITLE
FilePreference's get_storage override results in wrong storage.save() signature

### ISSUE THREAD

**Issue by macolo** [agateblue/django-dynamic-preferences#132]
it seems that django introduced the 'content' argument, but dynamic preferences seems to be calling storage without it.

https://github.com/django/django/blob/6e4c6281dbb7ee12bcdc22620894edb4e9cf623f/django/core/files/storage.py#L35

https://github.com/EliotBerriot/django-dynamic-preferences/blob/b54796e86d96a64900d78571b47a0cf0ab716aae/dynamic_preferences/serializers.py#L276

I am using this to make dynamic preferences overwrite the previous file via my own OverrideStorage class so that there are no funny numbers appended to file names.

**Comment by EliotBerriot** [comment]
Hi and thank you for the report. I'm not sure I understand the issue. Indeed, django's Storage expects a storage argument, in second position (if we exclude `self`). In the snippet you linked, we are passing `(path, f)` meaning `f` will be passed as the `content` argument, which looks okay to me.

Can you please elaborate or write a small test case demonstrating the issue so I can reproduce this locally?
