### ISSUE TITLE
Does it work with multiple servers?

### ISSUE THREAD

**Issue by luisccf** [agateblue/django-dynamic-preferences#171]
I have an application hosted in Amazon Elastic Beanstalk, with load balancing enabled. This means it launches multiple servers running the application, and distributes the users among them.

So if Elastic Beanstalk launches servers A and B, and a user changes a preference on admin while on server A, will server B update its value as well? All applications are connected to the same database.

**Comment by EliotBerriot** [comment]
Hi @luisccf! Yes, it's one of the supported use case. Preferences are stored in the database, so as long as you connect to the same database, everything should be fine.
