### ISSUE TITLE
filefield list_editable

### ISSUE THREAD

**Issue by zbynekdrlik** [agateblue/django-dynamic-preferences#178]
I am ussing FIlePreferences and ADMIN_ENABLE_CHANGELIST_FORM': True
Changing file in changelist view is not working. Save button doesn't know that file has been choosen.

**Comment by zbynekdrlik** [comment]
The source of problem is in formsets.py. It checks only one line in form because django predict that all lines are same Form classes. But in this module, every line could be different type.
So if on first line is filefield everything is ok. If no, files can't be uploaded.

```
    def is_multipart(self):
        """
        Return True if the formset needs to be multipart, i.e. it
        has FileInput, or False otherwise.
        """
        if self.forms:
            return self.forms[0].is_multipart()
        else:
            return self.empty_form.is_multipart()
```

Function should check all forms. I don't know how to override this function only for this module.

**Comment by zbynekdrlik** [comment]
Finally this is solution

```
class GpFormSet(BaseModelFormSet):
    # Patch for wrong dynamic_preferences listview multipart detection
    def is_multipart(self):
        return True

class CustomGlobalPreferenceAdmin(GlobalPreferenceAdmin):
    # Patch for wrong dynamic_preferences listview multipart detection
    def get_changelist_formset(self, request, **kwargs):
        kwargs['formset'] = GpFormSet
        return super().get_changelist_formset(request, **kwargs)
```

**Comment by EliotBerriot** [comment]
Thank you for sharing. Do you think there is anything to do on our side, or is your workaround enough?

**Comment by zbynekdrlik** [comment]
I think that it is still problem that should be patched in django-dynamic-preferences.

**Comment by EliotBerriot** [comment]
Thanks, I will leave the issue open then, and gladly accept a pull request that address this issue :)
