### ISSUE TITLE
Errors in docs for adding api urls

### ISSUE THREAD

**Issue by benwhalley** [agateblue/django-dynamic-preferences#233]
In the docs it suggests:

```
router.register(r"global", GlobalPreferencesViewSet, base_name="global")
```

But `base_name` is now deprecated by rest_framework in favour of `basename`. Changing the argument name fixes this error. 

Also, latest versions of Django throw and error when including urls like this:

```
url(r"^preferences/", include(router.urls, namespace="preferences"))
```

And instead it should be:

```
url(r"^preferences/", include((router.urls, "preferences"), namespace="preferences"))
```

**Comment by agateblue** [comment]
Closing, feel free to reopen / submit a PR if there is still something to fix on our side.
