### ISSUE TITLE
Readthedocs is not up to date

### ISSUE THREAD

**Issue by julienc91** [agateblue/django-dynamic-preferences#242]
Hello,

I just noticed that although [it is referenced in index.rst](https://github.com/agateblue/django-dynamic-preferences/blob/4dd668f1b60523c6205b1df653501b8b7ca9023b/docs/index.rst), the page [react_to_updates.rst](https://github.com/agateblue/django-dynamic-preferences/blob/4dd668f1b60523c6205b1df653501b8b7ca9023b/docs/react_to_updates.rst) is not visible on Readthedocs:

![](https://i.imgur.com/HLmUPnF.png)

**Comment by agateblue** [comment]
Fixed a while ago ;)
