### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by hansegucker** [agateblue/django-dynamic-preferences#245]
There are some commits waiting for being released. Among other things, there is one change (#244) which prevents the Free School Information System AlekSIS from releasing a stable version. Is there any progress with releasing a patch version?

**Comment by hansegucker** [comment]
Uff, what should we do now?

**Comment by debdolph** [comment]
Any progress?

**Comment by agateblue** [comment]
Would someone here would be interested to become co-maintainer of the package? I lack time to review pull requests lately, but I can help

**Comment by agateblue** [comment]
thank you @Natureshadow , I've sent you an invite :)

**Comment by Natureshadow** [comment]
Thanks!

How will be handle uploads to PyPI?

**Comment by agateblue** [comment]
@Natureshadow if that's okay, for you, I'll continue to do that myself for a little why, as I don't feel comfortable giving push access there to someone I haven't work with at least a bit :)
