### ISSUE TITLE
Caching behavior

### ISSUE THREAD

**Issue by henadzit** [agateblue/django-dynamic-preferences#247]
At the moment django-dynamic-preferences [caches values indefinitely](https://github.com/agateblue/django-dynamic-preferences/blob/4dd668f1b60523c6205b1df653501b8b7ca9023b/dynamic_preferences/managers.py#L112) if caching is used. There are potentials issues with this approach where the database and the cache get out of sync. There are a few examples of how this could happen:

- The process crashes or getting killed just after the setting has been stored in the database but the cache hasn't been updated yet
- A database backup is applied with an older version of the setting
- A redis backup is applied when redis is used as a cache backend

Having a timeout would also let to update the setting in the database directly without using Django. At the moment this would require clearing cache manually.

I see three potential paths to introduce more flexible caching:
- Remove `None` from arguments of the call `self.cache.set(key, value, None)` [here](https://github.com/agateblue/django-dynamic-preferences/blob/4dd668f1b60523c6205b1df653501b8b7ca9023b/dynamic_preferences/managers.py#L112). This will make Django to use the default cache timeout.
- Add a global option to specify the timeout. This approach seems to be used in [similar libraries](https://github.com/mikeengland/django-setty).
- Add a configuration option for timeout per preference.

Please let me know what you think and I can help with PR for this change.

**Comment by agateblue** [comment]
Hi there, I think it make sense to at least remove the `None` param in the `cache.set` to use the default cache value. Having a dedicated setting `dynamic_preferences` for this (defaulting to the default cache timeout) would also work great!

**Comment by henadzit** [comment]
@agateblue I've created [PR](https://github.com/agateblue/django-dynamic-preferences/pull/253) for using the default cache timeout. Could you please have a look?
