### ISSUE TITLE
Divide preferences by section in the admin interface - Signals problem

### ISSUE THREAD

**Issue by CapAlex94** [agateblue/django-dynamic-preferences#281]
Hi, first of all congratulations for the excellent extension!

I'm using the global_preference for different configurations inside my app, using the admin interface to allow users to update the configurations. I'm currently using 2 different section to define configurations. I would like to divide the "GLOBAL PREFERENCE" block by section in order to make more easily to update preferences of a specific section.

What i would like to create is something like the following structure:

global preferences
|
|_ Section 1
      |_ Conf 1
      |_ Conf 2
|
|_ Section 2
       |_ Conf 1
       |_ Conf 2

How can I create this structure inside the admin interface?

Second problem:

I'm trying to use signals to perform action when a preference is updated. At the moment, I'm following the documentation and I have create the callback function inside an utils.py file and I have registered the signal receiver inside the apps.py file inside one of the application of my Django project. I have updated one of the preference available using the admin interface but my callback function is not called. Is that normal or I am missing something?

Thanks for the support!!

**Comment by CapAlex94** [comment]
Hi it's possible to have an update about this topic? In particular about the signals when a settings is updated.

thanks

**Comment by agateblue** [comment]
(Sorry, I closed by mistake)

As for your second problem, can you please share the relevant code of each files?

**Comment by CapAlex94** [comment]
I used the same code provided by you on the wiki page (https://django-dynamic-preferences.readthedocs.io/en/latest/react_to_updates.html), no other custom code was created as the basic one was not working correctly.

**Comment by agateblue** [comment]
Is the app config in question installed in your `settings.INSTALLED_APPS`? Can you try putting a `raise` or `print('hello')` statement in the `ready()` function to ensure it is loaded properly py Django?

**Comment by CapAlex94** [comment]
Yes the apps.py is loaded by django on startup:

![image](https://user-images.githubusercontent.com/622099/186177911-da857972-fb06-4341-b522-e272eada3990.png)

**Comment by CapAlex94** [comment]
dashboard/apps.py

```
from django.apps import AppConfig
from dynamic_preferences.signals import preference_updated

from dashboard.utils import notify_on_preference_update


class DashboardConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'dashboard'


    def ready(self):
        print('Registering signals')
        preference_updated.connect(notify_on_preference_update)
```

```

**Comment by agateblue** [comment]
Thank you, I have reproduced it locally and published a fix. Can you please try the develop branch on your project and let me know if it works?

**Comment by CapAlex94** [comment]
Yes, now it's working correctly.

Thanks!!

**Comment by agateblue** [comment]
Alright, I'll publish a release on PyPi tomorrow :)

**Comment by agateblue** [comment]
Release 1.14.0 including this fix was just published on PyPi https://pypi.org/project/django-dynamic-preferences/1.14.0/#history

**Comment by CleitonDeLima** [comment]
I think that in this update the preferences per instance was not considered :thinking:
