### ISSUE TITLE
New release + Django 4 support?

### ISSUE THREAD

**Issue by jose-reveni** [agateblue/django-dynamic-preferences#294]
Is there a new release planned?
There is a warning about `django.utils.timezone.utc`, which will be deprecated in Django 5.0 (scheduled for relased in December this year).

The develop currently uses `datetime.timezone.utc` instead, so a new release with the current codebase would fix this warning

**Comment by agateblue** [comment]
I've just pushed release 1.15.0 to pypi : https://pypi.org/project/django-dynamic-preferences/1.15.0/

thank you for the reminder !
