### ISSUE TITLE
Querying all users with certain preference value

### ISSUE THREAD

**Issue by khankuan** [agateblue/django-dynamic-preferences#89]
Hi, I was wondering if anyone encountered a need to query for users that has the preference value set to a specific value, for example:
```
User.objects.filter(preference__ comment_notifications_enabled=True)
```
Cheers!

**Comment by EliotBerriot** [comment]
You should be able to do that, but I agree the API is not designed for such operations:

```python
from django.db.models import Q
User.objects.filter(userpreferencemodel__section='misc', userpreferencemodel__name='is_zombie', userpreferencemodel__raw_value='True')

query = Q(userpreferencemodel__name='comment_notifications_enabled') & \
            Q(userpreferencemodel__value='True')

queryset = User.objects.filter(query)
```

I can perfectly imagine adding a dedicated queryset for preferences to make this easier, I'll still have to think about the API.

Also, note that every preference value is stored as a string (booleans, numbers and other preferences are all serialized to string). If you have a lot of users and, therefore, a lot of preferences, querying on preferences values will be slower than what you could expect when filtering on a boolean. 

Depending on the size of your project and how much performance you need, using dynamic preferences to filter users on their preference value may not be the perfect fit.

**Comment by khankuan** [comment]
Ah i see, i'll try that thanks!

**Comment by rvignesh89** [comment]
@EliotBerriot considering that you have left this issue open, are you planning on implementing a dedicated API as you've suggested?

**Comment by EliotBerriot** [comment]
@rvignesh89 yes, this is something I have in mind  but I'm not 100% sure about the implementation.

I think we should be able to register some addditional queryset methods on preferences so someone can do something like `User.objects.filter(preferences__blog__comments_enabled__real_value=True)`, with the `real_value` lookup calling the preference serializer to convert the python value to the internal, db string, value.

This can only work on single preferences lookup though, as we need to know how to serialize the value, but it's still better than nothing.
